// Code generated by mockery v1.0.0. DO NOT EDIT.

package contractregistrymocks

import (
	contractregistry "github.com/hyperledger/firefly-ethconnect/internal/contractregistry"
	messages "github.com/hyperledger/firefly-ethconnect/internal/messages"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ContractStore is an autogenerated mock type for the ContractStore type
type ContractStore struct {
	mock.Mock
}

// AddABI provides a mock function with given fields: id, deployMsg, createdTime
func (_m *ContractStore) AddABI(id string, deployMsg *messages.DeployContract, createdTime time.Time) *contractregistry.ABIInfo {
	ret := _m.Called(id, deployMsg, createdTime)

	var r0 *contractregistry.ABIInfo
	if rf, ok := ret.Get(0).(func(string, *messages.DeployContract, time.Time) *contractregistry.ABIInfo); ok {
		r0 = rf(id, deployMsg, createdTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractregistry.ABIInfo)
		}
	}

	return r0
}

// AddContract provides a mock function with given fields: addrHexNo0x, abiID, pathName, registerAs
func (_m *ContractStore) AddContract(addrHexNo0x string, abiID string, pathName string, registerAs string) (*contractregistry.ContractInfo, error) {
	ret := _m.Called(addrHexNo0x, abiID, pathName, registerAs)

	var r0 *contractregistry.ContractInfo
	if rf, ok := ret.Get(0).(func(string, string, string, string) *contractregistry.ContractInfo); ok {
		r0 = rf(addrHexNo0x, abiID, pathName, registerAs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractregistry.ContractInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(addrHexNo0x, abiID, pathName, registerAs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddRemoteInstance provides a mock function with given fields: lookupStr, address
func (_m *ContractStore) AddRemoteInstance(lookupStr string, address string) error {
	ret := _m.Called(lookupStr, address)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(lookupStr, address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckNameAvailable provides a mock function with given fields: name, isRemote
func (_m *ContractStore) CheckNameAvailable(name string, isRemote bool) error {
	ret := _m.Called(name, isRemote)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(name, isRemote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *ContractStore) Close() {
	_m.Called()
}

// GetABI provides a mock function with given fields: location, refresh
func (_m *ContractStore) GetABI(location contractregistry.ABILocation, refresh bool) (*contractregistry.DeployContractWithAddress, error) {
	ret := _m.Called(location, refresh)

	var r0 *contractregistry.DeployContractWithAddress
	if rf, ok := ret.Get(0).(func(contractregistry.ABILocation, bool) *contractregistry.DeployContractWithAddress); ok {
		r0 = rf(location, refresh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractregistry.DeployContractWithAddress)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contractregistry.ABILocation, bool) error); ok {
		r1 = rf(location, refresh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContractByAddress provides a mock function with given fields: addrHex
func (_m *ContractStore) GetContractByAddress(addrHex string) (*contractregistry.ContractInfo, error) {
	ret := _m.Called(addrHex)

	var r0 *contractregistry.ContractInfo
	if rf, ok := ret.Get(0).(func(string) *contractregistry.ContractInfo); ok {
		r0 = rf(addrHex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractregistry.ContractInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(addrHex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocalABIInfo provides a mock function with given fields: abiID
func (_m *ContractStore) GetLocalABIInfo(abiID string) (*contractregistry.ABIInfo, error) {
	ret := _m.Called(abiID)

	var r0 *contractregistry.ABIInfo
	if rf, ok := ret.Get(0).(func(string) *contractregistry.ABIInfo); ok {
		r0 = rf(abiID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractregistry.ABIInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(abiID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *ContractStore) Init() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListABIs provides a mock function with given fields:
func (_m *ContractStore) ListABIs() []messages.TimeSortable {
	ret := _m.Called()

	var r0 []messages.TimeSortable
	if rf, ok := ret.Get(0).(func() []messages.TimeSortable); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]messages.TimeSortable)
		}
	}

	return r0
}

// ListContracts provides a mock function with given fields:
func (_m *ContractStore) ListContracts() []messages.TimeSortable {
	ret := _m.Called()

	var r0 []messages.TimeSortable
	if rf, ok := ret.Get(0).(func() []messages.TimeSortable); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]messages.TimeSortable)
		}
	}

	return r0
}

// ResolveContractAddress provides a mock function with given fields: registeredName
func (_m *ContractStore) ResolveContractAddress(registeredName string) (string, error) {
	ret := _m.Called(registeredName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(registeredName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(registeredName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
