// Code generated by mockery v1.0.0. DO NOT EDIT.

package ffcapiconnectormocks

import (
	context "context"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// FFCServer is an autogenerated mock type for the FFCServer type
type FFCServer struct {
	mock.Mock
}

// ServeFFCAPI provides a mock function with given fields: ctx, payload, w
func (_m *FFCServer) ServeFFCAPI(ctx context.Context, payload []byte, w http.ResponseWriter) {
	_m.Called(ctx, payload, w)
}
