// Code generated by mockery v2.39.2. DO NOT EDIT.

package saramamocks

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// ConsumerGroupClaim is an autogenerated mock type for the ConsumerGroupClaim type
type ConsumerGroupClaim struct {
	mock.Mock
}

// HighWaterMarkOffset provides a mock function with given fields:
func (_m *ConsumerGroupClaim) HighWaterMarkOffset() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HighWaterMarkOffset")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// InitialOffset provides a mock function with given fields:
func (_m *ConsumerGroupClaim) InitialOffset() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitialOffset")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Messages provides a mock function with given fields:
func (_m *ConsumerGroupClaim) Messages() <-chan *sarama.ConsumerMessage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 <-chan *sarama.ConsumerMessage
	if rf, ok := ret.Get(0).(func() <-chan *sarama.ConsumerMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *sarama.ConsumerMessage)
		}
	}

	return r0
}

// Partition provides a mock function with given fields:
func (_m *ConsumerGroupClaim) Partition() int32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Partition")
	}

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// Topic provides a mock function with given fields:
func (_m *ConsumerGroupClaim) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewConsumerGroupClaim creates a new instance of ConsumerGroupClaim. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerGroupClaim(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerGroupClaim {
	mock := &ConsumerGroupClaim{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
